### PR TITLE
C++ interface refinement for Genode

### PR DESCRIPTION
**Pull request by jklmnn**
Currently we use `block.h` and `block_class.cc` to implement the Genode C++ interface. While designing the server interface I notices some drawbacks in this design. With the ongoing development I'll do some refinements on the C++ backend to fix this. This includes moving code to shared headers that is used in both client and server (which unsurprisingly corresponds to shared types in Ada) and the renaming of especially `block.h` and `block_class.cc`.

### CODE REVIEW

**Comment by jklmnn** [comment]
Also warnings that should be fixed:
 - [ ] `cxx-block-server.adb:67:07: warning: "This" is not modified, could be declared constant`
 - [ ] `cxx-block-server.adb:75:26: warning: formal parameter "This" is not modified`
 - [ ] `cxx-block-server.adb:75:26: warning: mode could be "in" instead of "in out"`
 - [ ] `cxx-block-server.adb:85:24: warning: formal parameter "This" is not modified`
 - [ ] `cxx-block-server.adb:85:24: warning: mode could be "in" instead of "in out"`
 - [ ] `cxx-block-server.ads:4:09: warning: default constructor must be imported from C++`

**Comment by jklmnn** [comment]
https://github.com/Componolit/ada-interface/pull/5/commits/05fe6849b40207ee31c724986efa9f42d931ec71 needs https://github.com/jklmnn/genode/commit/42815506cbe0d0780edf612405c97600f0be5733 and https://github.com/Componolit/cbe/commit/b890f255983f02bd5893cf570174c849e4ade0f9

**Comment by senier** [comment]
We should make `Block.Context` a private type (new System.Address).

**Comment by jklmnn** [comment]
`Block.Context` is public and needs to be so to be visible for the platform implementation.

**Pull request closed without merging**
