### PR TITLE
Block tests

### PR DESCRIPTION
**Pull request by jklmnn**
Those are the block tests from the CBE repo including their dependencies as required. The code has been style checked but not yet proven.

### CODE REVIEW

**Comment by senier** [comment]
The `lib/permutation` directory should go to `test/lib/permutation` as we need the code only for testing and users could get confused about the purpose of this code.

**Comment by senier** [comment]
Do we really want to merge this to master with the CI failing?

**Comment by jklmnn** [comment]
Of course not, I forgot to check the tests locally. However I do not have an idea how to fix this. We should disable the proof for LSC here since we do not want to test LSC in this repo.

**Comment by senier** [comment]
The problem is that we include LSC using the `Source_Dirs` variable. This effectively makes it part of our own project and thus we have to prove it (which we can't right now). The canonical way to solve this is to build and install LSC somewhere and than use the [library project file](https://github.com/Componolit/libsparkcrypto/blob/master/build/libsparkcrypto.gpr) that's being installed. Libraries are not proven on inclusion.

**Comment by jklmnn** [comment]
I moved the permutation library and compile the libsparkcrypto as a library. Although I do use a custom gpr file for lsc since we're building against our own runtime. The tests succeed now.

**Pull request merged**
